server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: d990d0b1-cec0-4267-8b91-fa3fd851affa
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://nacos-order-consumer #匹配后提供服务的路由地址
          predicates:
            - Path=/order/payment/employee         # 断言，路径相匹配的进行路由
            - After=2023-05-08T16:13:38.487+08:00[Asia/Shanghai]
            #- Cookie=username,zhuyq
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Method=GET
          filters:
            # 过滤器为网关实现请求的鉴权功能，Gateway自带了几十个过滤器，能够为用户的请求修改很多参数。
            # 如：AddRequestHeader能够对匹配上的请求添加Header，AddRequestParematers能够为匹配上的请求路由添加参数，
            # AddResponseHeader能够为从网关上返回的响应添加Header。-AddResponseHeader=X-Response-Foo, Bar
            - AddRequestHeader=X-Request-Red,1024 # 过滤器工厂会在匹配的请求头上加上一堆请求头 名称为X-Request-Id 值为1024